/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2016-10-16 08:11:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.flp.ems.service.*;
import java.util.*;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;

public final class remove_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <title>EMS</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function isVerify(){\r\n");
      out.write("\tif (confirm('Are you sure you want to delete this employee?')) {\r\n");
      out.write("\t    return true;\r\n");
      out.write("\t} else {\r\n");
      out.write("\t    return false;\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t \r\n");
      out.write("\t\t \r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">EMS</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <ul class=\"nav navbar-nav\">\r\n");
      out.write("   <li ><a  href=\"add.jsp\">Add Employee</a></li>\r\n");
      out.write("    <li><a  href=\"modify.jsp\">Modify Employee</a></li>\r\n");
      out.write("    <li class=\"active\"><a  href=\"#\">Remove Employee</a></li>\r\n");
      out.write("    <li ><a  href=\"search.jsp\">Search Employee</a></li>\r\n");
      out.write("\t<li><a  href=\"display.jsp\">Display All Employees</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("      <li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\r\n");
      out.write("      <li><a href=\"#\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write(" \r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <div>\r\n");
      out.write("      <br>\r\n");
      out.write("\t  <br>\r\n");
      out.write("\t  <div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t<h4>Search an Employee</h4>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h4>by</h4>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"removeServlet\"  onsubmit=\"return isVerify()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<label><input type=\"radio\" name=\"remove\" value=\"kinId\">kin Id</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<label><input type=\"radio\" name=\"remove\" value=\"name\">name</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<label><input type=\"radio\" name=\"remove\" value=\"emailId\">email Id</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"form-control\" id=\"name\" placeholder=\"Value\" name=\"valueOfKey\">\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p>OR</p>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-group\">\r\n");
      out.write("      <label for=\"sel1\">Select an Employee from Summary :</label>\r\n");
      out.write("      <p>Kind ID&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\tEMAIL ID\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\tNAME\t&nbsp;&nbsp;&nbsp;&nbsp;\tROLE\t\t&nbsp;&nbsp;&nbsp;&nbsp;\tDEPARTMENT\t\t&nbsp;\t&nbsp;&nbsp;&nbsp;\tPROJECT</p>\r\n");
      out.write("      <select class=\"form-control\" id=\"sel1\" name=\"emailId\">\r\n");
      out.write("        ");
 
        HashMap<String, String> emp[];
		WebApplicationContext applicationContext = WebApplicationContextUtils.getRequiredWebApplicationContext(getServletContext());
		EmployeeServiceImpl e=applicationContext.getBean("service",EmployeeServiceImpl.class);
	emp=e.getAllEmployee();
		
	
		for(HashMap<String,String> hm:emp){

       
      out.write("\r\n");
      out.write("        <option value='");
      out.print( hm.get("emailId"));
      out.write('\'');
      out.write('>');
      out.print( hm.get("kinId"));
      out.write("&nbsp;&nbsp;&nbsp;");
      out.print(hm.get("emailId"));
      out.write("\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
      out.print(hm.get("name"));
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
      out.print(hm.get("role"));
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;");
      out.print(hm.get("dept"));
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;");
      out.print(hm.get("project") );
      out.write("</option>\r\n");
      out.write("\r\n");
		}
 
      out.write("        \r\n");
      out.write("      </select>\r\n");
      out.write("      <br>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t<input type=\"submit\" class=\"form-control\" value=\"Remove\" id=\"submit\">\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
